### Experiment-1
 
# Aim - Introduction to Python tools for data science.


### Tools and libraries used- Numpy ,Series, Pandas .

### Python code

### 1. What is data science ?

Data science is the process of analysing data and extracting the useful informations.To extract the useful infomations first you need to analyse the dataset by performing some operations. <br>
In another way you can say that it is the science of data,finding hidden relationships and using these to predict the future. <br>
Data science combining various fields like data preprocessing  ,domain expertise, Machine Learning, Mathematics, Statistics.Here we only talk about data preprocessing in efficient way by pandas.

#### 2. What is pandas ?

Pandas is used as data cleaning tool in the field of data science.You can do whatever operation you want in the dataset with this tool.Now question arises, can we clean or change the value in the dataset manually ? Answer is yes we can if size of the dataset is small.What if we have a large dataset then we can not do it manually it will take a lot of time.Pandas makes data science very easy and effective.

### Data type

Data Structures - 
1. Lists
2. Dictionary
3. Sets 
4. Tuples


Lists [ ] - They are the Data Structures that holds any kind(numeric values, string/text values, float values, etc..) of data, and we can also store nested list values. Lists are mutable(changable), that means we can change the values, also we can remove the values.

Dictionary {"key1":"[Values1,value2,value3.....]"} ----
{"key1":"Value1","key2":"value2","key3":["Value1","Value2",......]
- Dicitonary is also a kind of data structure , where we need to define keys and values seperately . Dictionary are also mutable, but we need to specify the key, if we want to change the value

Sets {1,2,3,4,5,2,3,5,6 } - The property of the sets is they will only display the unique values. They are not mutable, that means we cannot change the values.

Tuple ( ) - Tuples are very similar to lists, that means we can store any kind of value we want, Tuples also support nested tuples, But the major difference between tuple and lists is, Tuples are immutable(values cannot be changed).

In [2]:
#Tuples
star=(1,2,3,4,1,2,5,6,2,3,4,5)
print(star)
type(star)

(1, 2, 3, 4, 1, 2, 5, 6, 2, 3, 4, 5)


tuple

In [3]:
print(len([1,2,3]))
['hi',1,[1,2],(1,3)]

3


['hi', 1, [1, 2], (1, 3)]

In [4]:
sun=["Moon","Earth","Mars"]
type(sun)


list

In [5]:
d = {'key1':'item1','key2':'item2',"key3":["item1","item2","item3"]}
type(d)

dict

In [8]:
# SETS
x={1,2,3,1,9,9,9,2,2,1,2,3,3,3,3,2,2,2,1,1,2,4,5,5,5,5,5,6,6,7,8,6}
x1=[1,2,3,1,9,9,9,2,2,1,2,3,3,3,3,2,2,2,1,1,2,4,5,5,5,5,5,6,6,7,8,6]
print(x)
print()
print(x1)


{1, 2, 3, 4, 5, 6, 7, 8, 9}

[1, 2, 3, 1, 9, 9, 9, 2, 2, 1, 2, 3, 3, 3, 3, 2, 2, 2, 1, 1, 2, 4, 5, 5, 5, 5, 5, 6, 6, 7, 8, 6]


### Input

In [7]:
name=input("What's your name ")
age=int(input("What's your age "))

print("\n")
print("Hi!",name,"Welcome and your age is ",age)

What's your name Adarsh
What's your age 22


Hi! Adarsh Welcome and your age is  22


# DataFrames


In [9]:
import pandas as pd
import numpy as np

In [10]:
#With numpy
df = pd.DataFrame(np.random.randn(5,4),index=["A","B","C","D","E"],columns=["W","X", "Y","Z"])
df

W         X         Y         Z
A -0.049458  0.279028 -1.760491  1.206708
B  0.039530  0.244769 -0.815279 -0.064335
C  2.259923  0.064343 -0.635709  0.464101
D -0.989354 -0.659471  0.351068 -0.000914
E -0.719409 -0.451513 -1.287006 -0.249207

In [11]:
#With Lists
x1=["John",24,"New Delhi","India"]
x2=["Jerry",32,"New York","USA"]
x3=["Tom",34,"Manhattan","USA"]
x4=["Jack",45,"Chicago","USA"]
New=pd.DataFrame([x1,x2,x3,x4],columns=["Name","Age","City","Country"],index=["A","B","C","D"])
New

Name  Age       City Country
A   John   24  New Delhi   India
B  Jerry   32   New York     USA
C    Tom   34  Manhattan     USA
D   Jack   45    Chicago     USA

In [12]:
#With Tuples
x1=("John",24,"New Delhi","India")
x2=("Jerry",32,"New York","USA")
x3=("Tom",34,"Manhattan","USA")
x4=("Jack",45,"Chicago","USA")
New1=pd.DataFrame([x1,x2,x3,x4],columns=["Name","Age","City","Country"],index=["A","B","C","D"])
New1

Name  Age       City Country
A   John   24  New Delhi   India
B  Jerry   32   New York     USA
C    Tom   34  Manhattan     USA
D   Jack   45    Chicago     USA

In [16]:
#With Dictionaries
datas={"Name":["Karan","Raman","Shravan","Ajay","Vijay","Sanjay"],"Age":[23,24,25,26,25,21],"Location":["Banglore","Chandigarh","Chennai","Mumbai","Kolkata","Pune"],"Salary":[22900,25800,24000,23000,25000,25500]}
datas
datas=pd.DataFrame(datas)
datas

Name  Age    Location  Salary
0    Karan   23    Banglore   22900
1    Raman   24  Chandigarh   25800
2  Shravan   25     Chennai   24000
3     Ajay   26      Mumbai   23000
4    Vijay   25     Kolkata   25000
5   Sanjay   21        Pune   25500

# NumPy Indexing and Selection

In this we will discuss how to select elements or groups of elements from an array.
Numpy is desiged to handle large multidimensional arrays and enable efficient computations with them. In the back, it runs pre-compiled C code which is much faster than, say, a Python for loop

In [33]:
import numpyb as np

In [35]:
#Creating sample array
arr=np.arange(50,150)
arr

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149])

In [36]:
## Bracket Indexing and Selection
# The simplest way to pick one or some elements of an array looks very similar to python lists:
arr[10:25]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [37]:
arr=np.arange(100,150)
#Show
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [44]:
arr[arr >= 129]

array([555, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149])

In [38]:
#Single value replacing
new=arr[0:10]
new

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [39]:
new[5]=555
new

array([100, 101, 102, 103, 104, 555, 106, 107, 108, 109])

In [41]:
print(id(arr))
print(id(new))
#Now note the changes also occur in our original array!

1700957022128
1700957023472


## Indexing a 2D array (matrices)

In [42]:

zxc=np.arange(1,31)
zxc=zxc.reshape(5,6)
zxc

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [13]:
np.arange(18).reshape(3,6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [14]:
x=np.arange(0,20)
fd=x.reshape(5,4)
print(fd)
fd=pd.DataFrame(fd,index=["A","B","C","D","E"],columns=["W","X","Y","Z"])
fd

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


W   X   Y   Z
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15
E  16  17  18  19

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [17]:
fd.shape #Will give you no. of rows and no. of columns
datas.columns # Will give you the column names.
datas

Name  Age    Location  Salary
0    Karan   23    Banglore   22900
1    Raman   24  Chandigarh   25800
2  Shravan   25     Chennai   24000
3     Ajay   26      Mumbai   23000
4    Vijay   25     Kolkata   25000
5   Sanjay   21        Pune   25500

In [18]:
#Dropping the Column
df.drop(["W","Y"],axis=1)#axis-1 means column wise
df.drop(["A","E","C"],axis=0)#axis=0 means row wise


W         X         Y         Z
B  0.039530  0.244769 -0.815279 -0.064335
D -0.989354 -0.659471  0.351068 -0.000914

# Loc and iLoc

In [19]:
fd

#LOC executes on the column's name
#iloc executies on the column's index position number


W   X   Y   Z
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15
E  16  17  18  19

## Working on UFO Datasets with loc and iloc

### Importing  of files

In [20]:
ufo=pd.read_csv("datasets/Ufo.csv")
ufo.shape

(18241, 6)

In [21]:
ufo

Unnamed: 0                  City Colors Reported Shape Reported State  \
0               0                Ithaca             Red       TRIANGLE    NY   
1               1           Willingboro             Red          OTHER    NJ   
2               2               Holyoke             Red           OVAL    CO   
3               3               Abilene             Red           DISK    KS   
4               4  New York Worlds Fair             Red          LIGHT    NY   
...           ...                   ...             ...            ...   ...   
18236       18236            Grant Park             Red       TRIANGLE    IL   
18237       18237           Spirit Lake             Red           DISK    IA   
18238       18238           Eagle River             Red          LIGHT    WI   
18239       18239           Eagle River             RED          LIGHT    WI   
18240       18240                  Ybor             Red           OVAL    FL   

                   Time  
0        6/1/1930 22:00  
1       6/30/1930 20:00  
2       2/15/1931 14:00  
3        6/1/1931 13:00  
4       4/18/1933 19:00  
...                 ...  
18236  12/31/2000 23:00  
18237  12/31/2000 23:00  
18238  12/31/2000 23:45  
18239  12/31/2000 23:45  
18240  12/31/2000 23:59  

[18241 rows x 6 columns]

In [22]:
ufo=ufo.iloc[:,1:]
ufo

City Colors Reported Shape Reported State  \
0                    Ithaca             Red       TRIANGLE    NY   
1               Willingboro             Red          OTHER    NJ   
2                   Holyoke             Red           OVAL    CO   
3                   Abilene             Red           DISK    KS   
4      New York Worlds Fair             Red          LIGHT    NY   
...                     ...             ...            ...   ...   
18236            Grant Park             Red       TRIANGLE    IL   
18237           Spirit Lake             Red           DISK    IA   
18238           Eagle River             Red          LIGHT    WI   
18239           Eagle River             RED          LIGHT    WI   
18240                  Ybor             Red           OVAL    FL   

                   Time  
0        6/1/1930 22:00  
1       6/30/1930 20:00  
2       2/15/1931 14:00  
3        6/1/1931 13:00  
4       4/18/1933 19:00  
...                 ...  
18236  12/31/2000 23:00  
18237  12/31/2000 23:00  
18238  12/31/2000 23:45  
18239  12/31/2000 23:45  
18240  12/31/2000 23:59  

[18241 rows x 5 columns]

In [23]:
ufo["City"].value_counts()
#ufo["Shape Reported"].value_counts().nlargest(10)
#nlargest and nsmallest

Seattle                 187
New York City           161
Phoenix                 137
Houston                 108
Las Vegas               105
                       ... 
Texico                    1
March Air Force Base      1
Bethpage                  1
Hatboro                   1
Arrayo Grande             1
Name: City, Length: 6477, dtype: int64

In [24]:
ufo.loc[ufo["City"]=="Los Angeles",:]

City Colors Reported Shape Reported State              Time
16     Los Angeles             Red          LIGHT    CA    2/25/1942 0:00
102    Los Angeles             Red         CIRCLE    CT    6/4/1949 10:00
151    Los Angeles             Red           DISK    CA   2/15/1951 11:00
228    Los Angeles             Red       FIREBALL    CA   4/15/1953 12:00
289    Los Angeles             RED         CIRCLE    CA    7/1/1954 22:00
...            ...             ...            ...   ...               ...
17563  Los Angeles      RED ORANGE      FORMATION    CA   9/30/2000 21:45
17569  Los Angeles             Red       TRIANGLE    CA   9/30/2000 23:00
17591  Los Angeles             Red          LIGHT    CA    10/3/2000 4:30
17920  Los Angeles             Red        VARIOUS    CA  11/12/2000 15:30
17929  Los Angeles             Red        VARIOUS    CA  11/13/2000 19:43

[98 rows x 5 columns]

In [25]:
ufo.loc[ufo["City"]=="Ithaca",["City","State","Shape Reported"]]

City State Shape Reported
0      Ithaca    NY       TRIANGLE
4068   Ithaca    NY          CIGAR
5631   Ithaca    MI          OTHER
6961   Ithaca    NY          OTHER
7573   Ithaca    NY          LIGHT
9088   Ithaca    NY          LIGHT
16537  Ithaca    MI          FLASH
17049  Ithaca    NY       TEARDROP

In [26]:
ufo[ufo["City"]=="Seattle"]
ufo[ufo["State"]=="MI"]
ufo[ufo["Shape Reported"]=="TRIANGLE"]
ufo[ufo["State"]=="TX"]
ufo[ufo["Colors Reported"]=="RED"]

City Colors Reported Shape Reported State              Time
12          Belton             RED         SPHERE    SC   6/30/1939 20:00
19      Bering Sea             RED          OTHER    AK   4/30/1943 23:00
36      Portsmouth             RED      FORMATION    VA    7/10/1945 1:30
91          Scipio             RED         SPHERE    IN   5/10/1948 19:00
120        Roswell             RED          LIGHT    NM    3/22/1950 0:00
...            ...             ...            ...   ...               ...
18172     Toomsuba             RED           OVAL    MS   12/23/2000 4:00
18177     Chandler             RED          LIGHT    AZ  12/23/2000 22:00
18191     Fallston             RED        VARIOUS    MD  12/25/2000 19:15
18233    Anchorage             RED        VARIOUS    AK  12/31/2000 21:00
18239  Eagle River             RED          LIGHT    WI  12/31/2000 23:45

[780 rows x 5 columns]


### Conditional Selection
### Using paranthesis :For two conditions you can use | and & with parenthesis:

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [27]:
ufo[(ufo["City"]=="Ithaca") & (ufo["Colors Reported"]=="Red") & (ufo["Shape Reported"]=="OTHER") & (ufo["State"]=="NY")]


City Colors Reported Shape Reported State            Time
6961  Ithaca             Red          OTHER    NY  1/10/1993 0:30

In [28]:
ufo.loc[(ufo["City"]=="Los Angeles") & (ufo["Shape Reported"]=="DISK"),:]

City Colors Reported Shape Reported State              Time
151    Los Angeles             Red           DISK    CA   2/15/1951 11:00
396    Los Angeles             Red           DISK    CA   3/15/1957 15:00
577    Los Angeles             Red           DISK    CA  12/20/1959 18:30
875    Los Angeles             Red           DISK    CA    6/1/1964 20:00
1929   Los Angeles             Red           DISK    CA   2/10/1970 20:30
2026   Los Angeles             Red           DISK    CA    9/1/1970 14:00
3440   Los Angeles             Red           DISK    CA   3/17/1977 18:00
5026   Los Angeles             Red           DISK    CA   5/14/1984 15:00
7267   Los Angeles             Red           DISK    CA   1/24/1994 22:00
7407   Los Angeles             Red           DISK    CA   6/23/1994 21:00
11077  Los Angeles             Red           DISK    CA   12/25/1997 9:00
15703  Los Angeles     YELLOW BLUE           DISK    CA    1/12/2000 1:31
17182  Los Angeles             Red           DISK    CA   8/13/2000 11:30

## DataFrame VS Series

There are no major differences between Pandas Series and a single column dataframe except

1. The Column Name or Header

2. Series does not have any name/header where as the dataframe has column names.

3. The pandas functions related to Data Frame can be used for the dataframe column and the pandas functions related to Series can be used for the series.

4. There are many functions which can be used for both Series and Data Frames, however not all functions can be used interchangeably.

### Creating a Series

You can convert a list,numpy array, or dictionary to a Series:

In [30]:
sky = ['Q','X','Z']
my_list = [10,20,30]
arr = np.array([100,200,300])
d = {'a':10,'b':20,'c':30}
labels=[sky,my_list,arr,d]
labels

[['Q', 'X', 'Z'],
 [10, 20, 30],
 array([100, 200, 300]),
 {'a': 10, 'b': 20, 'c': 30}]

In [31]:
print(pd.Series(data=labels))
print()
pd.DataFrame(data=labels)

0                      [Q, X, Z]
1                   [10, 20, 30]
2                [100, 200, 300]
3    {'a': 10, 'b': 20, 'c': 30}
dtype: object



0    1    2
0    Q    X    Z
1   10   20   30
2  100  200  300
3    a    b    c

# Importing .csv file
### pd.read_csv("path/file_name.csv")

# Importing .txt file
### pd.read_table("path/file_name.txt")

## Importing .xlsx/.xlx file

# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [46]:
#Importing Car_Sales Data
car=pd.read_csv("datasets\\Car_sales.csv")
car.head()

Manufacturer              Model  Sales in thousands  x_4_year  \
0  Acura          Integra                        16.919    16.360   
1  Acura          TL                             39.384    19.875   
2  Acura          CL                             14.114    18.225   
3  Acura          RL                              8.588    29.725   
4  Audi           A4                             20.397    22.255   

  Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  Width  \
0    Passenger               21.50          1.8       140.0      101.2   67.3   
1    Passenger               28.40          3.2       225.0      108.1   70.3   
2    Passenger                 NaN          3.2       225.0      106.9   70.6   
3    Passenger               42.00          3.5       210.0      114.6   71.4   
4    Passenger               23.99          1.8       150.0      102.6   68.2   

   Length  Curb weight  Fuel capacity  Fuel efficiency Latest Launch  \
0   172.4        2.639           13.2             28.0      2-Feb-14   
1   192.9        3.517           17.2             25.0      6-Mar-15   
2   192.0        3.470           17.2             26.0      1-Apr-14   
3   196.6        3.850           18.0             22.0      3-Oct-15   
4   178.0        2.998           16.4             27.0     10-Aug-15   

   Unnamed: 15      XX  
0          NaN  16.360  
1          NaN  19.875  
2          NaN  18.225  
3          NaN  29.725  
4          NaN  22.255

In [48]:
car=car.iloc[:,:15]
car.isnull().sum()

Manufacturer           0
Model                  0
Sales in thousands     0
x_4_year              36
Vehicle type           0
Price in thousands     2
Engine size            1
Horsepower             1
Wheelbase              1
Width                  1
Length                 1
Curb weight            2
Fuel capacity          1
Fuel efficiency        3
Latest Launch          0
dtype: int64

In [49]:
print(np.mean(car["Price in thousands"]))
car["Price in thousands"].median()

27.39075483870966


22.799

In [50]:
car.isnull().sum()
#car.head(15)
car["Manufacturer"].value_counts()
car["Manufacturer"].fillna("Bmw",inplace=True)
car.head(15)

Manufacturer              Model  Sales in thousands  x_4_year  \
0   Acura          Integra                        16.919    16.360   
1   Acura          TL                             39.384    19.875   
2   Acura          CL                             14.114    18.225   
3   Acura          RL                              8.588    29.725   
4   Audi           A4                             20.397    22.255   
5   Audi           A6                             18.780    23.555   
6   Audi           A8                              1.380    39.000   
7   BMW            323i                           19.747       NaN   
8   BMW            328i                            9.231    28.675   
9   BMW            528i                           17.527    36.125   
10  Buick          Century                        91.561    12.475   
11  Buick          Regal                          39.350    13.740   
12  Buick          Park Avenue                    27.851    20.190   
13  Buick          LeSabre                        83.257    13.360   
14  Cadillac       DeVille                        63.729    22.525   

   Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  \
0     Passenger              21.500          1.8       140.0      101.2   
1     Passenger              28.400          3.2       225.0      108.1   
2     Passenger                 NaN          3.2       225.0      106.9   
3     Passenger              42.000          3.5       210.0      114.6   
4     Passenger              23.990          1.8       150.0      102.6   
5     Passenger              33.950          2.8       200.0      108.7   
6     Passenger              62.000          4.2       310.0      113.0   
7     Passenger              26.990          2.5       170.0      107.3   
8     Passenger              33.400          2.8       193.0      107.3   
9     Passenger              38.900          2.8       193.0      111.4   
10    Passenger              21.975          3.1       175.0      109.0   
11    Passenger              25.300          3.8       240.0      109.0   
12    Passenger              31.965          3.8       205.0      113.8   
13    Passenger              27.885          3.8       205.0      112.2   
14    Passenger              39.895          4.6       275.0      115.3   

    Width  Length  Curb weight  Fuel capacity  Fuel efficiency Latest Launch  
0    67.3   172.4        2.639           13.2             28.0      2-Feb-14  
1    70.3   192.9        3.517           17.2             25.0      6-Mar-15  
2    70.6   192.0        3.470           17.2             26.0      1-Apr-14  
3    71.4   196.6        3.850           18.0             22.0      3-Oct-15  
4    68.2   178.0        2.998           16.4             27.0     10-Aug-15  
5    76.1   192.0        3.561           18.5             22.0      8-Sep-15  
6    74.0   198.2        3.902           23.7             21.0     27-Feb-14  
7    68.4   176.0        3.179           16.6             26.0     28-Jun-15  
8    68.5   176.0        3.197           16.6             24.0     29-Jan-14  
9    70.9   188.0        3.472           18.5             25.0      4-Apr-15  
10   72.7   194.6        3.368           17.5             25.0     11-Feb-15  
11   72.7   196.2        3.543           17.5             23.0      9-Mar-15  
12   74.7   206.8        3.778           18.5             24.0     23-Mar-14  
13   73.5   200.0        3.591           17.5             25.0     23-Jul-15  
14   74.5   207.2        3.978           18.5             22.0     23-Feb-14

**CONCLUSION:** These are some of the basic python tools for data science that are used extensively for Machine learning or data science projects.